language: php
php:
  - 5.4

branches:
  only:
    - master

env:
  global:
    # PAGODABOX_USERNAME
    - secure: "h/VfDkDVOmUArakQM6IgTV5DnrnjXlFSM0R7Spea0vE++97E1kuQYxzbflkr\n6aTQxbT7RLr0/F3r9Izae9dpmFJBRLrmIUja1faxVTCqJ5yj3d8xSKrnIQPF\nt+JfcRQ2uY3VQOwZ8h4uU+9buOsvY4DAPalF45vznetshpm65hs="
    # PAGODABOX_PASSWORD
    - secure: "agaXjfEgmKdu8Qhe6Ja/F+e9VWZQolWpQciTbhJXfcN9Lr279rKOWr72np9w\nIrJxeqLIGYnv0BXHzreDE3IvkQ2aj4rqD2hL8tgTt133VNIl8qhWXWHlx227\nmJOm66STh6jTaIzeri4RXQuGRaxfNiwWH4x4eJCDGlElhZ7qp2c="
    # PAGODABOX_APP
    - secure: "MqVeafPuLtRtp9xzkrFyUxC1Rx5L9dNFk98M9EP0/s6VCXGa3/4GuxajBm9A\nhZ5gImvJ8MGaMVjFViHU7P/umgrwp3ZJQ4xWgpcux1FjDiJi1krXMX86TZoR\nheUrUaIjgUuunJ7mJGhzdcdLUfSpG4chZndSt+k8GMW64Alzs1M="

script:
  - echo 'Travis run' # tests would be here.
  # deployment from here down.
  - gem install pagoda
  - pagoda --username=$PAGODABOX_USERNAME --password=$PAGODABOX_PASSWORD --app=$PAGODABOX_APP init
  - ssh-keygen -N "" -f ~/.ssh/pagoda
  - pagoda --username=$PAGODABOX_USERNAME --password=$PAGODABOX_PASSWORD --app=$PAGODABOX_APP key:push --file=$HOME/.ssh/pagoda.pub
  - echo "Host git.pagodabox.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - echo "   IdentityFile=${HOME}/.ssh/pagoda" >> ~/.ssh/config
  - echo "   IdentitiesOnly yes" >> ~/.ssh/config
  - git push --force pagoda master
  - pagoda --username=$PAGODABOX_USERNAME --password=$PAGODABOX_PASSWORD --app=$PAGODABOX_APP deploy